### ISSUE TITLE
Cannot run repo with instructions in Readme.md 'Test My Repo'

### ISSUE THREAD

**Issue by simon-tarr** [sunilale0/Django-Stripe-Checkout#2]
Hello, 

I have cloned the repo, started a venv and installed dependencies in requirements.txt (as per your instructions). However, I can't work out how to follow this instuction:

> I have used a separate settings file called user_settings.py in djangostripe/ to hard code these secret keys and client ids. I have import this file somewhere at the bottom in djangostripe/settings.py.

I get an error on line 123 in settings.py: `from .user_settings import *`

```
  File "/Users/st/Documents/Django-Stripe-Checkout/djangostripe/settings.py", line 123, in <module>
    from .user_settings import *
ModuleNotFoundError: No module named 'djangostripe.user_settings'
```

Are there some extra steps I need to do before `runserver` will work successfully?

Thanks!

**Comment by elabdesunil** [comment]
What I did there was I created `user_settings.py` on the same directory as `settings.py`, and imported the file using the line `from .user_settings import *`.

So, did you create `user_settings.py` at `djangostripe/` directory and put the values mentioned [here](https://github.com/sunilale0/Django-Stripe-Checkout#test-my-repo) `STRIPE_PUBLISHABLE_KEY` and the other variables?
